### ISSUE TITLE
Add null safety support

### ISSUE THREAD

**Issue by behnamsattar** [RainwayApp/flutter_home_indicator#7]

**Comment by azeek** [comment]
I hope this problem is solved quickly.

**Comment by light-speak** [comment]
I hope this problem is solved quickly.

**Comment by alexmarkley** [comment]
Thanks so much for this package! This package is a huge help to me and my app definitely depends on it.

I agree that null safety support would be very helpful.

**Comment by nohli** [comment]
You can use my migrated fork for now:

```
  home_indicator:
    git:
      url: https://github.com/nohli/flutter_home_indicator
      ref: migrate-to-nnbd
```

Also @lynn could merge the PR and publish a new stable version to pub.dev.
